server:
  port: 1010
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?autoReconnect=true
    username: root
    password: p.123456
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: none
